### ISSUE TITLE
argus_webodm     | WARNING Bad Request: /api/token-auth/

### ISSUE THREAD

**Issue by roblab2011** [RoblabWh/argus#1]
When sending to opendronemap i got a argus_webodm     | WARNING Bad Request: /api/token-auth/
in the terminal

**Comment by SchulteM42** [comment]
This issue may arise due to the use of an older webODM image that may not support the single-user mode. To resolve this, consider pulling a new WebODM image using './argus.sh pull --ignore-buildable' and then rebuild the server with './argus.sh up --build'.

It's worth noting that receiving a warning like 'Bad Request: /api/token-auth/' is quite normal during startup, as the container may not be fully started when the first request is sent. However, if you encounter more than a couple of these warnings during the argus startup, it's recommended to follow the procedure mentioned above to update WebODM.
