### ISSUE TITLE
Using the odm_data_aukerman example files: Composite:FOV, XMP:FlightYawDegree does not exist in EXIF-Header

### ISSUE THREAD

**Issue by fabpiaf** [RoblabWh/argus#10]
```
argus            | ___UNUSABLE___ Error while loading relative altitude
argus            | __UNUSABLE__ Error while loading camera properties: Composite:FOV does not exist in EXIF-Header of input image: ./static/projects/2411251526575088/rgb/DSC00281.JPG
argus            | __UNUSABLE__ Error while loading orientation: XMP:FlightYawDegree does not exist in EXIF-Header of input image: ./static/projects/2411251526575088/rgb/DSC00281.JPG
```

The preprocessing freezes at about 75% without user feedback (web interface). Console shows the above.
How to fix the exif data? Is this just a key problem of metadata? webodm handles the files successfully.

Probably b.c. its not a DJI?
What else is DJI specific? (in respect to what is needed to introduce other drone models)

**Comment by SchulteM42** [comment]
Hello, at the moment, data from most DJI drones and Parrot drones can be processed. For our fast mapping, GPS data is required, along with the gimbal's orientation and the drone's relative altitude above the ground.
Regardless, the report should still be generated, with the map generation being skipped. WebODM should still be able to process it. I will try to fix this.

**Comment by fabpiaf** [comment]
So the Exif keys for said values are the only reason that only DJI is supported out of the box?

**Comment by SchulteM42** [comment]
Kind of—Anafi Ai is also supported. On one hand, the EXIF keys need to be defined (or match the default), and on the other hand, the required data must be available in the first place (your example is missing some necessary information).
I went through the mentioned dataset to check what might be causing the problem. As you already suggested, the camera/UAV was not yet supported, so I tried adding the necessary keys for map calculation. It turns out that while there are some orientation values in the XMP data, the relative altitude above ground is missing, and no information about the field of view (FOV) or sensor size is provided.
The FOV can be calculated beforehand and stored as a default value (which I also tried), but this still didn’t give me the relative altitude. Additionally, the orientation values use a different format compared to those from DJI and Anafi. For example, DJI uses 0° for looking straight ahead and -90° for looking straight down, while this dataset seems to use +0° for straight down and 90° for straight towards the horizon.

Nevertheless, a report should still be generated, even without the maps. I am currently working on fixing this.

**Comment by SchulteM42** [comment]
I applied some changes. Your dataset will now generate a new report, but due to the missing altitude data (and the other mentioned metadata issues), Argus fast mapping will not be performed. Nevertheless, thank you for your tests and for highlighting these issues. Your dataset revealed another minor flaw that might have affected half the world (or at least their coordinates). Perhaps testing only our datasets from flights within Germany wasn’t the best approach.

Since the Argus crash in your case is now resolved, I will close this issue. Regarding the fast mapping, this cannot be performed with the provided dataset.
